# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Build
    jobs:
      - job: BuildWebApp
        variables:
          buildConfiguration: 'Release'

        pool:
          vmImage: 'windows-latest'

        steps:
        - task: DotNetCoreCLI@2
          displayName: 'Build API Getway Project'
          inputs:
            command: 'publish'
            publishWebProjects: true
            projects: '**/APIGetway/APIGetway.csproj'
            arguments: '--configuration $(buildConfiguration) --output $(Build.BinariesDirectory)/$(Build.BuildId)'
            modifyOutputPath: false
        - task: DotNetCoreCLI@2
          displayName: 'Build Oder Service Project'
          inputs:
            command: 'publish'
            publishWebProjects: true
            projects: '**/OrderService/OrderService.csproj'
            arguments: '--configuration $(buildConfiguration) --output $(Build.BinariesDirectory)/$(Build.BuildId)'
            modifyOutputPath: false 
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Web Artifact'
          inputs:
            PathtoPublish: '$(Build.BinariesDirectory)/$(Build.BuildId)'
            ArtifactName: 'drop-$(Build.BuildId)'
            publishLocation: 'Container'